//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdisyonOdemeDetay
    {
        public int AdisyonOdemeDetayID { get; set; }
        public int AdisyonID { get; set; }
        public int OdemeYontemiID { get; set; }
        public string OdemeYontemiAdi { get; set; }
    
        public virtual Adisyon Adisyon { get; set; }
        public virtual OdemeYontemi OdemeYontemi { get; set; }
    }
}
