//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepoMalzemeDetay
    {
        public int DepoMalzemeID { get; set; }
        public int DepoID { get; set; }
        public int MalzemeID { get; set; }
        public int DepoStok { get; set; }
    
        public virtual Depo Depo { get; set; }
        public virtual Malzeme Malzeme { get; set; }
    }
}
