//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzeme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Malzeme()
        {
            this.DepoMalzemeDetay = new HashSet<DepoMalzemeDetay>();
            this.RestaurantMalzemeDetay = new HashSet<RestaurantMalzemeDetay>();
            this.UrunMalzemeDetay = new HashSet<UrunMalzemeDetay>();
        }
    
        public int MalzemeID { get; set; }
        public string MalzemeAdi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> MalzemeKategoriID { get; set; }
        public Nullable<int> TedarikciID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepoMalzemeDetay> DepoMalzemeDetay { get; set; }
        public virtual MalzemeKategori MalzemeKategori { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantMalzemeDetay> RestaurantMalzemeDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunMalzemeDetay> UrunMalzemeDetay { get; set; }
    }
}
