//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Marla_Ado1Entities : DbContext
    {
        public Marla_Ado1Entities()
            : base("name=Marla_Ado1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adisyon> Adisyon { get; set; }
        public virtual DbSet<AdisyonOdemeDetay> AdisyonOdemeDetay { get; set; }
        public virtual DbSet<AdisyonSiparisDetay> AdisyonSiparisDetay { get; set; }
        public virtual DbSet<Calisan> Calisan { get; set; }
        public virtual DbSet<CalisanDetay> CalisanDetay { get; set; }
        public virtual DbSet<Depo> Depo { get; set; }
        public virtual DbSet<DepoMalzemeDetay> DepoMalzemeDetay { get; set; }
        public virtual DbSet<Malzeme> Malzeme { get; set; }
        public virtual DbSet<MalzemeKategori> MalzemeKategori { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MenuKategori> MenuKategori { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<OdemeYontemi> OdemeYontemi { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
        public virtual DbSet<RestaurantMalzemeDetay> RestaurantMalzemeDetay { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<Tedarikci> Tedarikci { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<UrunMalzemeDetay> UrunMalzemeDetay { get; set; }
        public virtual DbSet<UrunSiparisDetay> UrunSiparisDetay { get; set; }
    }
}
