//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantMalzemeDetay
    {
        public int RestaurantMalzemeDetay1 { get; set; }
        public int MalzemeID { get; set; }
        public int RestaurantId { get; set; }
        public Nullable<int> RestaurantStok { get; set; }
    
        public virtual Malzeme Malzeme { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
