//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.AdisyonSiparisDetay = new HashSet<AdisyonSiparisDetay>();
            this.UrunSiparisDetay = new HashSet<UrunSiparisDetay>();
        }
    
        public int SiparisID { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
        public Nullable<bool> SiparisTuru { get; set; }
        public Nullable<int> MasaNumarası { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> CalisanId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdisyonSiparisDetay> AdisyonSiparisDetay { get; set; }
        public virtual Calisan Calisan { get; set; }
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunSiparisDetay> UrunSiparisDetay { get; set; }
    }
}
