//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunSiparisDetay
    {
        public int UrunSiparisDetayID { get; set; }
        public int UrunID { get; set; }
        public int SiparisID { get; set; }
        public Nullable<int> SiparisMiktari { get; set; }
        public decimal Fiyat { get; set; }
    
        public virtual Siparis Siparis { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
