//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunMalzemeDetay
    {
        public int UrunMalzemeID { get; set; }
        public int UrunID { get; set; }
        public int MalzemeID { get; set; }
        public int MalzemeStok { get; set; }
    
        public virtual Malzeme Malzeme { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
